module.exports = [
  {
    name: 'SEOmatic',
    src: 'nystudio107/craft-seomatic',
    handle: 'seomatic',
    checked: true,
  },
  {
    name: 'Imager X',
    src: 'spacecatninja/imager-x',
    handle: 'imager-x',
    checked: true,
  },
  {
    name: 'SVG Placeholder',
    src: 'mblode/svgplaceholder',
    handle: 'svgplaceholder',
    checked: true,
  },
  {
    name: 'Wordsmith',
    src: 'topshelfcraft/wordsmith',
    handle: 'wordsmith',
    checked: true,
  },
  {
    name: 'Asset Rev',
    src: 'clubstudioltd/craft-asset-rev',
    handle: 'assetrev',
    checked: true,
  },
  {
    name: 'AWS S3 Asset Source',
    src: 'craftcms/aws-s3',
    handle: 'aws-s3',
    checked: true,
  },
  {
    name: 'Blitz',
    src: 'putyourlightson/craft-blitz',
    handle: 'blitz',
    checked: true,
  },
  {
    name: 'Snitch',
    src: 'marionnewlevant/snitch',
    handle: 'snitch',
    checked: true,
  },
  {
    name: 'Twig Perversion',
    src: 'marionnewlevant/twig-perversion',
    handle: 'twig-perversion',
    checked: true,
  },
  {
    name: 'Ray',
    src: 'spatie/craft-ray',
    handle: 'craft-ray',
    checked: true,
  },
  {
    name: 'Environment Label',
    src: 'topshelfcraft/environment-label',
    handle: 'environment-label',
    checked: true,
  },
  {
    name: 'Expanded Singles',
    src: 'verbb/expanded-singles',
    handle: 'expanded-singles',
    checked: true,
  },
  {
    name: 'Redactor',
    src: 'craftcms/redactor',
    handle: 'redactor',
    checked: true,
  },
  {
    name: 'Typed Link Field',
    src: 'sebastianlenz/linkfield',
    handle: 'typedlinkfield',
    checked: true,
  },
  {
    name: 'CP Field Inspect',
    src: 'mmikkel/cp-field-inspect',
    handle: 'cp-field-inspect',
    checked: true,
  },
  {
    name: 'Supertable',
    src: 'verbb/super-table',
    handle: 'super-table',
    checked: true,
  },
  {
    name: 'Empty Coalesce',
    src: 'nystudio107/craft-emptycoalesce',
    handle: 'empty-coalesce',
    checked: true,
  },
  {
    name: 'Matrix Mate',
    src: 'vaersaagod/matrixmate',
    handle: 'matrixmate',
    checked: true,
  },
  {
    name: 'Autocomplete',
    src: 'nystudio107/craft-autocomplete',
    handle: 'autocomplete',
    installable: false,
    checked: true,
  },
];
